server {
    listen 80;
    listen [::]:80;
    server_name m.bugcatcher.online mobile.bugcatcher.online;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name m.bugcatcher.online mobile.bugcatcher.online;

    root /var/www/bugcatcher-mobileweb;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ /\.(?!well-known) {
        deny all;
    }

    ssl_certificate /etc/letsencrypt/live/bugcatcher-mobileweb/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bugcatcher-mobileweb/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
